
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useUnicode=yes&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": false
        "[show_sql]": false
        jdbc:
          lob:
            "[non_contextual_creation]": true
    defer-datasource-initialization: true
  sql:
    init.mode: always
    init.encoding: UTF-8
